name = "nthumods-api"
main = "src/index.ts"
compatibility_date = "2025-03-06"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "api.nthumods.com", custom_domain = true }
]
minify = true

[dev]
port = 5001
local_protocol = "http"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "data-d1"
database_id = "c6b4c91d-35a1-4218-9226-a8ab217150fb"

[[ratelimits]]
name = "VENUE_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 100
  period = 60
